# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Extract < Formula
  desc "file extractor"
  homepage ""
  version "0.1.8"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.8/util-enable_Darwin_arm64.tar.gz"
      sha256 "c16a70ccaa8e691a3d329959787e465d604f288a59cfed34a84d6fde57e8eb48"

      def install
        bin.install "extract"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.8/util-enable_Darwin_x86_64.tar.gz"
      sha256 "64dbc76f74c3a95496e6947fb48414f694fcc245675c7bb009cb0530911f33d1"

      def install
        bin.install "extract"
      end
    end
  end
end
