# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Extract < Formula
  desc "file extractor"
  homepage "https://github.com/terencendabereye/util-extract"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.5/util-extract_Darwin_arm64.tar.gz"
      sha256 "1463e67d4ee67b9e21bd48a4ac98fa78afb7616d4394c8acf04c04693cb7b515"

      def install
        bin.install "extract"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.5/util-extract_Darwin_x86_64.tar.gz"
      sha256 "c4e9ed4e7a0620d0d750906f6e5d1d83604ae95e5e314822a76e3846e426b0dd"

      def install
        bin.install "extract"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.5/util-extract_Linux_x86_64.tar.gz"
      sha256 "8a99e53f637c871b1049090011ab2a9525171000eceaa7b4fcdb9c70af1c5d15"

      def install
        bin.install "extract"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.5/util-extract_Linux_arm64.tar.gz"
      sha256 "115d6678bcf824e1b96f94b7c89a899ee1d0b25d323f9a4abfee9ed562e72368"

      def install
        bin.install "extract"
      end
    end
  end
end
