# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Extract < Formula
  desc "file extractor"
  homepage ""
  version "0.1.6"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.6/util-enable_Darwin_arm64.tar.gz"
      sha256 "352ac67f0f3ef9bbcec94cfceb4695c01a25ea645717239c78f8f7f55b745d21"

      def install
        bin.install "util-enable"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.1.6/util-enable_Darwin_x86_64.tar.gz"
      sha256 "9ae6c90421c757d4ee8275a409cfa08a5eea003e08f45232f0ebf03725a5b911"

      def install
        bin.install "util-enable"
      end
    end
  end
end
