# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Extract < Formula
  desc "file extractor"
  homepage "https://github.com/terencendabereye/util-extract"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.2.1/file-extraction-utility_Darwin_arm64.tar.gz"
      sha256 "5bb8858969f330b285e0ecde9ae865316bcc115fba5d676980fb9231eefb7340"

      def install
        bin.install "extract"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.2.1/file-extraction-utility_Darwin_x86_64.tar.gz"
      sha256 "b95e9c529540fda1a1c961f61f91de4544f50816e81c610b0540a9a3f5d05579"

      def install
        bin.install "extract"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.2.1/file-extraction-utility_Linux_arm64.tar.gz"
      sha256 "367d8bae9cb7046950771bc924ec6b9a7f21400e0608d8aa622ac075702facdf"

      def install
        bin.install "extract"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/terencendabereye/util-extract/releases/download/v0.2.1/file-extraction-utility_Linux_x86_64.tar.gz"
      sha256 "e36c67e346d014e394f9275beb30d9b25eb4c8c19a2d9224b172047df411694c"

      def install
        bin.install "extract"
      end
    end
  end
end
